services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=163.123.183.89
      - DB_PORT=17705
      - DB_NAME=ecole2026
      - DB_USER=ecole
      - DB_PASSWORD=peda2026

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "5173:5173"
