ALTER TABLE Evaluation DROP FOREIGN KEY Evaluation_ibfk_1;
ALTER TABLE Frequente DROP FOREIGN KEY Frequente_ibfk_3;
ALTER TABLE Paiement DROP FOREIGN KEY Paiement_ibfk_1;
ALTER TABLE Parents DROP FOREIGN KEY Parents_ibfk_4;
ALTER TABLE Rapport DROP FOREIGN KEY Rapport_ibfk_1;

ALTER TABLE Eleve MODIFY matricule VARCHAR(50) NOT NULL;
ALTER TABLE Evaluation MODIFY matricule VARCHAR(50) NOT NULL;
ALTER TABLE Frequente MODIFY matricule VARCHAR(50) NOT NULL;
ALTER TABLE Paiement MODIFY matricule VARCHAR(50) NOT NULL;
ALTER TABLE Parents MODIFY matricule VARCHAR(50) NOT NULL;
ALTER TABLE Rapport MODIFY matricule VARCHAR(50) NOT NULL;

ALTER TABLE Evaluation ADD CONSTRAINT Evaluation_ibfk_1 FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Frequente ADD CONSTRAINT Frequente_ibfk_3 FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Paiement ADD CONSTRAINT Paiement_ibfk_1 FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Parents ADD CONSTRAINT Parents_ibfk_4 FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Rapport ADD CONSTRAINT Rapport_ibfk_1 FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Personne
ADD COLUMN nom VARCHAR(60) DEFAULT '',
ADD COLUMN prenom VARCHAR(60) DEFAULT '',
ADD COLUMN sexe CHAR(1) DEFAULT 'M',
ADD COLUMN dateNaissance DATE DEFAULT '2000-01-01',
ADD COLUMN email VARCHAR(100) DEFAULT '',
ADD COLUMN telephone1 VARCHAR(30) DEFAULT '';
