services:
  - type: web
    name: ecole-api
    env: node
    buildCommand: npm install -g pnpm && pnpm install && pnpm build
    startCommand: cd apps/api && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
