services:
  - type: web
    name: digischool-api
    runtime: node
    repo: https://github.com/TemeIsrael/DIGISCHOOL
    plan: free
    region: oregon
    buildCommand: pnpm install && pnpm build
    startCommand: cd apps/api && pnpm start
    rootDir: .
    envVars:
      - key: PNPM_VERSION
        value: 9.1.0
      - key: DB_HOST
        value: mysql-digischool-temeisrael65-91e3.b.aivencloud.com
      - key: DB_PORT
        value: 24262
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: israel235
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
