services:
  - type: web
    name: digischool-api
    runtime: node
    plan: free
    region: oregon
    rootDir: ecole-app
    buildCommand: pnpm install && pnpm build --filter @ecole-app/shared && pnpm build --filter @ecole-app/api
    startCommand: cd apps/api && pnpm start
    envVars:
      - key: PNPM_VERSION
        value: 9.1.0
      - key: DB_HOST
        value: 163.123.183.89
      - key: DB_PORT
        value: 17705
      - key: DB_USER
        value: ecole
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: ecole2026
      - key: DB_SSL
        value: true
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
